#!/usr/bin/with-contenv bash

# Env variable validation
VARS=( \
INDEX_PROVIDER \
API_KEY \
NZBGET_HOST
)
for i in "${VARS[@]}"; do
  if [ -z ${!i+x} ]; then
    echo "[cont-init.d] ${i} is required and is not set will not continue"
    exit 0
  fi
done

# Check if this is a fresh container run service briefly to create database
if [ ! -f "/config/nzbdrone.db" -a ! -f "/config/radarr.db" ]; then
  (mono /app/radarr/bin/Radarr.exe \
  -nobrowser -data=/config > /dev/null 2>&1) & PID=$!
  while [ ! -f "/config/nzbdrone.db" -a ! -f "/config/radarr.db" ];
  do
      echo "waiting for Radarr to create a DB..."
      sleep 1
  done
  # Set database name
  if [ -f "/config/radarr.db" ]; then
    DBNAME=radarr
  else
    DBNAME=nzbdrone
  fi
  # Loop to detect file changes
  while true;
  do
      echo "waiting for database schema import..."
      if [ -z ${COMPARE_MD5+x} ]; then
        COMPARE_MD5=$(md5sum /config/${DBNAME}.db| cut -c1-8)
        sleep 3
      else
        sleep 3
        CURRENT_MD5=$(md5sum /config/${DBNAME}.db| cut -c1-8)
        if [ "${CURRENT_MD5}" == ${COMPARE_MD5} ]; then
          break
        else
          COMPARE_MD5=$(md5sum /config/${DBNAME}.db| cut -c1-8)
        fi
      fi
  done
  # If previous loop caught a race condition check to make sure NamingConfig exists
  while ! /usr/bin/sqlite3 /config/${DBNAME}.db 'select * from NamingConfig' > /dev/null 2>&1;
  do
    echo "checking for DB import..."
    sleep 1
  done
  # On init the ReplaceIllegalCharacters column in NamingConfig is the last DB migration we require
  while [[ "$(/usr/bin/sqlite3 /config/${DBNAME}.db '.schema NamingConfig')" != *"ReplaceIllegalCharacters"* ]];
  do
    echo "final DB import check..."
    sleep 1
  done
  sleep 1
  while kill -0 $PID; do
    sleep 1
    kill $PID
  done
else
  echo "[cont-init.d] This container is already configured"
  exit 0
fi

# Set port to default if unset
if [ -z ${NZBGET_PORT+x} ]; then
  NZBGET_PORT="6789"
fi

# Set variables based on index provider passed
if [ "${INDEX_PROVIDER}" == "Nzbplanet" ]; then
  INDEX_NAME="nzbplanet.net"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.nzbplanet.net"
  INDEX_CATAGORIES="[2000,2010,2020,2030,2040,2050,2060]"
  INDEX_CONFIG="NewznabSettings"
elif [ "${INDEX_PROVIDER}" == "Miatrix" ]; then
  INDEX_NAME="miatrix.com"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.miatrix.com/"
  INDEX_CATAGORIES="[2000,2010,2020,2030,2035,2040,2045,2050,2060]"
  INDEX_CONFIG="NewznabSettings"
elif [ "${INDEX_PROVIDER}" == "NZBgeek" ]; then
  INDEX_NAME="nzbgeek.info"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.nzbgeek.info"
  INDEX_CATAGORIES="[2000,2010,2020,2030,2035,2040,2045,2050,2060]"
  INDEX_CONFIG="NewznabSettings"
elif [ "${INDEX_PROVIDER}" == "NZBsu" ]; then
  INDEX_NAME="Nzb.su"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.nzb.su"
  INDEX_CATAGORIES="[2000,2010,2020,2030,2035,2040,2045,2050,2060]"
  INDEX_CONFIG="NewznabSettings"
elif [ "${INDEX_PROVIDER}" == "usenet-crawler" ]; then
  INDEX_NAME="Usenet Crawler"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://www.usenet-crawler.com"
  INDEX_CATAGORIES="[2000,2010,2020,2030,2035,2040,2045,2050,2060]"
  INDEX_CONFIG="NewznabSettings"
else
  echo "[cont-init.d] Your Provider ${INDEX_PROVIDER} is not recognized will not continue"
  exit 0
fi

# Insert our fresh config into the database
/usr/bin/sqlite3 /config/${DBNAME}.db "\
  INSERT INTO \
  Indexers(\
    'Name',\
    'Implementation',\
    'Settings',\
    'ConfigContract',\
    'EnableRss',\
    'EnableSearch') \
  VALUES(\
    \"${INDEX_NAME}\",\
    \"${INDEX_TYPE}\",\
    '{\
      \"baseUrl\": \"${INDEX_URL}\",\
      \"multiLanguages\": [],\
      \"apiKey\": \"${API_KEY}\",\
      \"categories\": ${INDEX_CATAGORIES},\
      \"animeCategories\": [],\
      \"removeYear\": false,\
      \"searchByTitle\": false\
    }',\
     \"${INDEX_CONFIG}\",1,1);"
/usr/bin/sqlite3 /config/${DBNAME}.db "\
  INSERT INTO \
  DownloadClients(\
    'Enable',\
    'Name',\
    'Implementation',\
    'Settings',\
    'ConfigContract') \
  VALUES(\
    1,\
    'nzbget',\
    'Nzbget',\
    '{\
      \"host\": \"${NZBGET_HOST}\",\
      \"port\": ${NZBGET_PORT},\
      \"username\": \"nzbget\",\
      \"password\": \"null\",\
      \"movieCategory\": \"Movies\",\
      \"recentMoviePriority\": 0,\
      \"olderMoviePriority\": 0,\
      \"useSsl\": false,\
      \"addPaused\": false\
    }',\
    'NzbgetSettings');"
/usr/bin/sqlite3 /config/${DBNAME}.db "\
  INSERT INTO \
    NamingConfig(\
      'MultiEpisodeStyle',\
      'RenameEpisodes',\
      'ReplaceIllegalCharacters',\
      'StandardMovieFormat',\
      'MovieFolderFormat',\
      'ColonReplacementFormat') \
    VALUES(\
      0,\
      1,\
      1,\
      '{Movie Title} ({Release Year})',\
      '{Movie Title} ({Release Year})',\
      0);"
/usr/bin/sqlite3 /config/${DBNAME}.db "\
  UPDATE NamingConfig SET \
    'MultiEpisodeStyle' = 0,\
    'RenameEpisodes' = 1,\
    'ReplaceIllegalCharacters' = 1,\
    'StandardMovieFormat' = '{Movie Title} ({Release Year})',\
    'MovieFolderFormat' = '{Movie Title} ({Release Year})',\
    'ColonReplacementFormat' = 0"
/usr/bin/sqlite3 /config/${DBNAME}.db "\
  INSERT INTO \
    RootFolders('Path') \
    VALUES('/data/movies');"
/usr/bin/sqlite3 /config/${DBNAME}.db "\
  INSERT INTO \
    Restrictions(\
      'Ignored',\
      'Tags')\
    VALUES(\
      '.3D.,.AC3D.,.AC3LD.,.AC3MD.,.CAM.,.DTSD.,.HC.,.HD-TS.,HEVC,x265,.HDCAM.,.HQDTS.,.HQHDTS.,.ISO.,.R5.,.R6.,.SCR.,.TELESYNC.,.TS.,divx,dksub,dubbed,dvd9,FGT,hdrip,hebrew,hebsubs,hqcam,hevc,korsub,multisubs,swesub,truefrench,xvid,yify,AVC,2160p,BDSCR,BRrip,CAM,CAMRIP,core2hd,divx,DVDSCR,DVDSCREENER,HD2DVD,HDCAM,HDChina,HDTS,Micromkv,PDVD,SCR,SCREENER,TELECINE,TELESYNC,WORKPRINT,WP,XviD',\
      '[]');"

# permissions
mkdir -p /data/movies
chown abc:abc \
  /data \
  /data/movies
