#!/usr/bin/with-contenv bash

# Env variable validation
VARS=( \
INDEX_PROVIDER \
API_KEY \
NZBGET_HOST
)
for i in "${VARS[@]}"; do
  if [ -z ${!i+x} ]; then
    echo "[cont-init.d] ${i} is required and is not set will not continue"
    exit 0
  fi
done

# Check if this is a fresh container run service briefly to create database
if [ ! -f "/config/lidarr.db" ]; then
  (mono /app/lidarr/bin/Lidarr.exe \
  -nobrowser -data=/config > /dev/null 2>&1) & PID=$!
  while [ ! -f "/config/lidarr.db" ];
  do
      echo "waiting for Lidarr to create a DB..."
      sleep 1
  done
  # Loop to detect file changes
  while true;
  do
      echo "waiting for database schema import..."
      if [ -z ${COMPARE_MD5+x} ]; then
        COMPARE_MD5=$(md5sum /config/lidarr.db| cut -c1-8)
        sleep 3
      else
        sleep 3
        CURRENT_MD5=$(md5sum /config/lidarr.db| cut -c1-8)
        if [ "${CURRENT_MD5}" == ${COMPARE_MD5} ]; then
          break
        else
          COMPARE_MD5=$(md5sum /config/lidarr.db| cut -c1-8)
        fi
      fi
  done
  # If previous loop caught a race condition check to make sure NamingConfig exists
  while ! /usr/bin/sqlite3 /config/lidarr.db 'select * from NamingConfig' > /dev/null 2>&1;
  do
    echo "checking for DB import..."
    sleep 1
  done
  # On init the ReplaceIllegalCharacters column in NamingConfig is the last DB migration we require
  while [[ "$(/usr/bin/sqlite3 /config/lidarr.db '.schema NamingConfig')" != *"ReplaceIllegalCharacters"* ]];
  do
    echo "final DB import check..."
    sleep 1
  done
  sleep 1
  while kill -0 $PID; do
    sleep 1
    kill $PID
  done
else
  echo "[cont-init.d] This container is already configured"
  exit 0
fi

# Set port to default if unset
if [ -z ${NZBGET_PORT+x} ]; then
  NZBGET_PORT="6789"
fi

# Set variables based on index provider passed
if [ "${INDEX_PROVIDER}" == "Nzbplanet" ]; then
  INDEX_NAME="nzbplanet.net"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.nzbplanet.net"
  INDEX_CATAGORIES="[3000,3010,3020,3030,3040]"
  INDEX_CONFIG="NewznabSettings"
  INDEX_PATH="/api"
elif [ "${INDEX_PROVIDER}" == "Miatrix" ]; then
  INDEX_NAME="miatrix.com"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.miatrix.com/"
  INDEX_CATAGORIES="[3000,3010,3020,3030,3040]"
  INDEX_CONFIG="NewznabSettings"
  INDEX_PATH="/api"
elif [ "${INDEX_PROVIDER}" == "NZBgeek" ]; then
  INDEX_NAME="nzbgeek.info"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.nzbgeek.info"
  INDEX_CATAGORIES="[3000,3010,3020,3030,3040]"
  INDEX_CONFIG="NewznabSettings"
  INDEX_PATH="/api"
elif [ "${INDEX_PROVIDER}" == "NZBsu" ]; then
  INDEX_NAME="Nzb.su"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://api.nzb.su"
  INDEX_CATAGORIES="[3000,3010,3020,3030,3040]"
  INDEX_CONFIG="NewznabSettings"
  INDEX_PATH="/api"
elif [ "${INDEX_PROVIDER}" == "usenet-crawler" ]; then
  INDEX_NAME="Usenet Crawler"
  INDEX_TYPE="Newznab"
  INDEX_URL="https://www.usenet-crawler.com"
  INDEX_CATAGORIES="[3000,3010,3020,3030,3040]"
  INDEX_CONFIG="NewznabSettings"
  INDEX_PATH="/api"
else
  echo "[cont-init.d] Your Provider ${INDEX_PROVIDER} is not recognized will not continue"
  exit 0
fi

# Insert our fresh config into the database
/usr/bin/sqlite3 /config/lidarr.db "\
  INSERT INTO \
  Indexers(\
    'Name',\
    'Implementation',\
    'Settings',\
    'ConfigContract',\
    'EnableRss',\
    'EnableAutomaticSearch',
    'EnableInteractiveSearch') \
  VALUES(\
    \"${INDEX_NAME}\",\
    \"${INDEX_TYPE}\",\
    '{\
      \"baseUrl\": \"${INDEX_URL}\",\
      \"apiPath\": \"${INDEX_PATH}\",\
      \"apiKey\": \"${API_KEY}\",\
      \"categories\": ${INDEX_CATAGORIES}
    }',\
     \"${INDEX_CONFIG}\",1,1,1);"
/usr/bin/sqlite3 /config/lidarr.db "\
  INSERT INTO \
  DownloadClients(\
    'Enable',\
    'Name',\
    'Implementation',\
    'Settings',\
    'ConfigContract') \
  VALUES(\
    1,\
    'nzbget',\
    'Nzbget',\
    '{\
      \"host\": \"${NZBGET_HOST}\",\
      \"port\": ${NZBGET_PORT},\
      \"username\": \"nzbget\",\
      \"password\": \"null\",\
      \"musicCategory\": \"Music\",\
      \"recentMoviePriority\": 0,\
      \"olderMoviePriority\": 0,\
      \"useSsl\": false,\
      \"addPaused\": false\
    }',\
    'NzbgetSettings');"
/usr/bin/sqlite3 /config/lidarr.db "\
  INSERT INTO \
    NamingConfig(\
      'ReplaceIllegalCharacters',\
      'ArtistFolderFormat',\
      'RenameTracks',\
      'StandardTrackFormat',\
      'AlbumFolderFormat') \
    VALUES(\
      1,\
      '{Artist Name}',\
      1,\
      '{Artist Name} - {Album Title} - {track:00} - {Track Title}',\
      '{Album Title} ({Release Year})');"
/usr/bin/sqlite3 /config/lidarr.db "\
  INSERT INTO \
    RootFolders('Path') \
    VALUES('/data/music');"

# permissions
mkdir -p /data/music
chown abc:abc \
	/data \
  /data/music
